name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! We appreciate your ideas for improving ABADA Music Studio.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed these steps
      options:
        - label: I have searched existing feature requests
          required: true
        - label: I have checked the roadmap (docs/ROADMAP.md)
          required: true
        - label: This feature doesn't exist in the latest version
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Installation & Setup
        - Music Generation (AI)
        - User Interface
        - Performance
        - Gallery & Community
        - Documentation
        - Accessibility
        - Integrations
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm frustrated when...
        It would be helpful if...
        Currently, users cannot...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        I would like to see...
        The feature should work by...
        Example workflow:
        1. User does X
        2. System does Y
        3. Result is Z
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: |
        I also thought about...
        Another approach could be...
        Similar features in other tools...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who benefits from this feature and how?
      placeholder: |
        - Benefit 1: Helps beginners by...
        - Benefit 2: Saves time for advanced users...
        - Benefit 3: Improves accessibility by...

  - type: dropdown
    id: priority
    attributes:
      label: Priority (from your perspective)
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would significantly improve my experience
        - Critical for my use case
        - Blocking my ability to use the product
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, screenshots, or links to examples
      placeholder: |
        Drag and drop images here, or paste links to examples

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations (Optional)
      description: If you have technical knowledge, share implementation ideas
      placeholder: |
        - This could be implemented using...
        - Potential challenges might include...
        - Dependencies might be...

  - type: dropdown
    id: willingness
    attributes:
      label: Would you like to implement this?
      description: Are you willing to contribute to this feature?
      options:
        - I can implement this myself (with guidance)
        - I can help test this feature
        - I can help with documentation
        - I can provide feedback during development
        - I can sponsor/fund development
        - I'd just like to request this feature
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: |
        - Related features or issues
        - Reference implementations
        - Community feedback
