name: Security Vulnerability
description: Report a security issue (PRIVATE - use email for sensitive issues)
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Important: Responsible Disclosure

        **For sensitive security vulnerabilities, please email: security@abada.kr instead of using this public form.**

        Only use this form for:
        - Non-sensitive security concerns
        - Public dependency vulnerabilities
        - Security best practice suggestions

        For sensitive issues (unauthorized access, data exposure, etc.), please email us privately first.

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm you understand the above
      options:
        - label: I understand this is a public form
          required: true
        - label: This issue is NOT a sensitive security vulnerability
          required: true
        - label: I have considered responsible disclosure practices
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Estimated Severity
      description: How severe do you consider this issue?
      options:
        - Low (minor security improvement)
        - Medium (potential security concern)
        - High (significant security issue)
        - Critical (urgent security vulnerability)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Dependency vulnerability
        - Input validation
        - Authentication/Authorization
        - Data exposure
        - Code injection
        - Cross-site scripting (XSS)
        - Insecure configuration
        - Information disclosure
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      options:
        - Installer (Windows)
        - Installer (macOS)
        - Installer (Linux)
        - Desktop Application
        - Website (music.abada.kr)
        - API/Backend
        - Documentation
        - Dependencies
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the security concern (avoid sensitive details if public)
      placeholder: |
        What is the security issue?
        What could an attacker potentially do?
        Who is affected?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if applicable)
      description: How can this issue be demonstrated?
      placeholder: |
        1. Go to...
        2. Do...
        3. Observe...

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if this vulnerability is exploited?
      placeholder: |
        - Affected users: (e.g., all users, Windows users only)
        - Data at risk: (e.g., local files, user preferences)
        - Potential actions: (e.g., code execution, data theft)
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have ideas for fixing this, please share
      placeholder: |
        Possible solutions:
        - Update dependency X to version Y
        - Add input validation for Z
        - Change configuration to...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to CVEs, security advisories, or relevant documentation
      placeholder: |
        - CVE-YYYY-XXXXX
        - https://...
        - Related issue: #123

  - type: input
    id: version
    attributes:
      label: Affected Version(s)
      description: Which versions are affected?
      placeholder: "e.g., v1.0.0, v1.0.1"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Have you verified this issue?
        - Is this actively being exploited?
        - Any workarounds available?
